/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tutorial;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class tutorialConstants {

  /**
   * Constants can be defined, these can be used in the generated code as well.
   */
  public static final int INT32CONSTANT = 9853;

  public static final java.util.Map<java.lang.String,java.lang.String> MAPCONSTANT = new java.util.HashMap<java.lang.String,java.lang.String>();
  static {
    MAPCONSTANT.put("goodnight", "moon");
    MAPCONSTANT.put("hello", "world");
  }

}
